### PR TITLE
New Animations

### PR DESCRIPTION
**Pull request by arendruni**
## What was done?
* Added: 18 new animations

## Why?
As noted on issue #69 Apple published a video with new animations on their jobs.apple.com website, so I added them to Brooklyn as single animations.

## Screenshots
These are the 18 new animations that I added:

output_col6x3

_Cuphead2_ animation is slightly different from the one that's already in Brooklyn, so I kept them both.

### CODE REVIEW

**Comment by smolz** [comment]
Can we get this merged?

**Comment by kcmannem** [comment]
+1 would love if this got released

**Comment by cn-xufei** [comment]
How to release

**Comment by arendruni** [comment]
Can we get this merged, @pedrommcarrasco?

**Comment by pedrommcarrasco** [comment]
I'm sorry, I have this on my backlog for ages and never actually managed to review it. I'll do it today.

**Comment by pedrommcarrasco** [comment]
@arendruni can you please give me write access to your fork? I'd like to do some changes before merging it.

**Comment by arendruni** [comment]
> @arendruni can you please give me write access to your fork? I'd like to do some changes before merging it.

Done

**Review by pedrommcarrasco — APPROVED** [review]
So, here's what I changed:
- Handled huge merge conflict for you 
- Removed some animations that didn't loop nicely

**Comment by arendruni** [comment]
Looks good to me 👍

**Comment by arendruni** [comment]
@pedrommcarrasco, thanks for merging this! 
I think that issue #69 should be closed now.

**Pull request merged**
