### PR TITLE
[wip] Isolate animations

### PR DESCRIPTION
**Pull request by kjhx**
## What was done?
* Isolated animation `appleBits.mp4`
* Isolated animation `doodle.mp4`

### CODE REVIEW

**Comment by pedrommcarrasco** [comment]
Looking good so far! 🥇 
I would maybe play with reverses in `doodle` but it's fine as it is 😄

**Comment by pedrommcarrasco** [comment]
Hey @kjhx do you want to merge this and then you add more if you have time?

**Comment by kjhx** [comment]
Sure thing. I'll edit the doodle animation before the next pull request.

**Comment by pedrommcarrasco** [comment]
Just to confirm I got it right, you want me to wait until you edit the doodle animation before I merge this right? @kjhx

**Comment by pedrommcarrasco** [comment]
Also, let's try to avoid using the name **Apple** as it would be easily applied to every animation. With this mind, please rename `appleBits` to `bits`. This name might change in a later state but let's be coherent for now

**Pull request merged**
